title: docTR OCR Add-On
description: An Add-On that uses the open source [docTR](https://github.com/mindee/doctr) to OCR your documents. 
instructions: ''
type: object
documents:
  - selected
properties: {}
categories: 
  - extraction
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
